### ISSUE TITLE
高分屏縮放有問題，文字模糊。

### ISSUE THREAD

**Issue by wzy9607** [inkitter/pdx-ymltranslator#4]

**Comment by inkitter** [comment]
哪里导致的？我没超过1080p的屏幕，没试过。还是用windows自带的缩放导致的？

**Comment by wzy9607** [comment]
https://docs.microsoft.com/en-us/dotnet/framework/winforms/high-dpi-support-in-windows-forms
我試了下只添加manifest 會出問題。
![image](https://user-images.githubusercontent.com/17695588/30898481-1d74c60a-a38e-11e7-8b0f-e15618faef1c.png)
